// <auto-generated />
namespace NewsWeb.Models
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DBInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBInit));
        
        string IMigrationMetadata.Id
        {
            get { return "202401180620384_DBInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
